# -*- coding: utf-8 -*-
"""Self-Pruning Neural Network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I4ikAids4YwoufByekfRUzkZBAx-t5Eo
"""

"""
Self-Pruning Neural Network
Author: Nitin Gupta
Description: Implements dynamic pruning using learnable gates and L1 regularization.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import math
import urllib.error


# Prunable Linear Layer

class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super(PrunableLinear, self).__init__()
        self.in_features = in_features
        self.out_features = out_features

        self.weight = nn.Parameter(torch.Tensor(out_features, in_features))
        self.bias = nn.Parameter(torch.Tensor(out_features))
        self.gate_scores = nn.Parameter(torch.Tensor(out_features, in_features))

        self.reset_parameters()

    def reset_parameters(self):
        nn.init.kaiming_uniform_(self.weight, a=math.sqrt(5))
        if self.bias is not None:
            fan_in, _ = nn.init._calculate_fan_in_and_fan_out(self.weight)
            bound = 1 / math.sqrt(fan_in) if fan_in > 0 else 0
            nn.init.uniform_(self.bias, -bound, bound)

        # Initialize active
        nn.init.constant_(self.gate_scores, 1.0)

    def forward(self, x):
        gates = torch.sigmoid(self.gate_scores)
        pruned_weights = self.weight * gates
        return F.linear(x, pruned_weights, self.bias)

#Network Architecture

class SelfPruningMLP(nn.Module):
    def __init__(self):
        super(SelfPruningMLP, self).__init__()
        self.flatten = nn.Flatten()
        self.fc1 = PrunableLinear(3072, 512)
        self.fc2 = PrunableLinear(512, 256)
        self.fc3 = PrunableLinear(256, 10)

    def forward(self, x):
        x = self.flatten(x)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def get_sparsity_loss(self):
        loss = 0.0
        for module in self.modules():
            if isinstance(module, PrunableLinear):
                gates = torch.sigmoid(module.gate_scores)
                loss += torch.sum(gates)
        return loss

    def get_sparsity_level(self, threshold=1e-2):
        total_weights = 0
        pruned_weights = 0
        with torch.no_grad():
            for module in self.modules():
                if isinstance(module, PrunableLinear):
                    gates = torch.sigmoid(module.gate_scores)
                    total_weights += gates.numel()
                    pruned_weights += torch.sum(gates < threshold).item()

        return (pruned_weights / total_weights) * 100 if total_weights > 0 else 0

    def get_all_gates(self):
        all_gates = []
        with torch.no_grad():
            for module in self.modules():
                if isinstance(module, PrunableLinear):
                    gates = torch.sigmoid(module.gate_scores)
                    all_gates.append(gates.flatten())
        return torch.cat(all_gates)


# Training & Evaluation

def train_and_evaluate(lmbda, device, train_loader, test_loader, epochs=5):
    print(f"\n--- Training with Lambda = {lmbda} ---")
    model = SelfPruningMLP().to(device)
    criterion = nn.CrossEntropyLoss()

    gate_params = []
    base_params = []
    for name, param in model.named_parameters():
        if 'gate_scores' in name:
            gate_params.append(param)
        else:
            base_params.append(param)


    optimizer = optim.Adam([
        {'params': base_params, 'lr': 0.001},
        {'params': gate_params, 'lr': 1.0}
    ])

    for epoch in range(epochs):
        model.train()
        running_loss = 0.0

        for inputs, labels in train_loader:
            inputs, labels = inputs.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(inputs)

            classification_loss = criterion(outputs, labels)
            sparsity_loss = model.get_sparsity_loss()
            total_loss = classification_loss + (lmbda * sparsity_loss)

            total_loss.backward()
            optimizer.step()

            running_loss += total_loss.item()

        print(f"Epoch [{epoch+1}/{epochs}] Loss: {running_loss/len(train_loader):.4f}")

    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for inputs, labels in test_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    accuracy = 100 * correct / total
    sparsity = model.get_sparsity_level(threshold=1e-2)

    print(f"Test Accuracy: {accuracy:.2f}% | Sparsity Level: {sparsity:.2f}%")
    return model, accuracy, sparsity

def main():
    device = torch.device("cpu")
    print(f"Using device: {device} (Bypassing incompatible GPU)")

    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
    ])

    try:
        print("Attempting to load CIFAR-10...")
        train_dataset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
        test_dataset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)
        print("Successfully loaded CIFAR-10.")
    except (urllib.error.URLError, TimeoutError) as e:
        print(f"\n[!] NETWORK TIMEOUT: Falling back to synthetic mock data.")


        train_dataset = torchvision.datasets.FakeData(size=2500, image_size=(3, 32, 32), num_classes=10, transform=transform)
        test_dataset = torchvision.datasets.FakeData(size=500, image_size=(3, 32, 32), num_classes=10, transform=transform)


    train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=0)
    test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=32, shuffle=False, num_workers=0)


    lambda_values = [0.0, 0.05, 0.5]
    results = []
    models = {}

    for lmbda in lambda_values:
        model, acc, sparsity = train_and_evaluate(lmbda, device, train_loader, test_loader, epochs=5)
        results.append((lmbda, acc, sparsity))
        models[lmbda] = model

    print("\n\n### Results Summary Table")
    print(r"| Lambda ($\lambda$) | Test Accuracy (%) | Sparsity Level (%) |")
    print(r"| :--- | :---: | :---: |")
    for lmbda, acc, sparsity in results:
        print(f"| {lmbda} | {acc:.2f} | {sparsity:.2f} |")

    best_lambda = lambda_values[-1]
    best_model = models[best_lambda]
    gates_tensor = best_model.get_all_gates().cpu().numpy()

    plt.figure(figsize=(10, 6))
    plt.hist(gates_tensor, bins=50, color='teal', edgecolor='black')
    plt.title(rf'Distribution of Gate Values ($\lambda$ = {best_lambda})')
    plt.xlabel('Gate Value (Sigmoid Output)')
    plt.ylabel('Frequency')
    plt.yscale('log')
    plt.grid(True, alpha=0.3)
    plt.savefig('gate_distribution.png', dpi=300, bbox_inches='tight')
    print("\nPlot saved as 'gate_distribution.png'")

if __name__ == '__main__':
    main()